title: Valdinei Ferreira | Blog
author: Valdinei Ferreira
email: valdineifer@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Blog pessoal de Valdinei Ferreira. Neste blog, irei postar soluções 
  de problemas que enfrentei, dicas, sugestões de sites e cursos, 
  enfim, quaisquer conhecimentos e experiências que eu desejar 
  compartilhar com vocês.

# social links
twitter_username: _valdineifer
github_username:  valdineifer

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
